### ISSUE TITLE
Valores Predeterminados causes errors

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1043]
syspass version: most current beta 3.0.0.18090201

![grafik](https://user-images.githubusercontent.com/5631071/45918701-46a8cf80-be8b-11e8-90c6-30f483356047.png)

![grafik](https://user-images.githubusercontent.com/5631071/45918700-3bee3a80-be8b-11e8-872d-76fde92c4afb.png)

The syspass.log does not contain an error:
`tail -f syspass.log
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:16:02 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:16:02 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:12 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-09-22 17:18:12 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-09-22 17:18:12 [DEBUG] [SP\Bootstrap::run] ------------
2018-09-22 17:18:12 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-09-22 17:18:12 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-09-22 17:18:12 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-09-22 17:18:12 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-09-22 17:18:13 [DEBUG] [SP\Core\Language::setLocales] Locale set to: de_DE.utf8
2018-09-22 17:18:13 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-09-22 17:18:13 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-09-22 17:18:13 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-09-22 17:18:13 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-09-22 17:18:13 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\SyslogHandler
2018-09-22 17:18:13 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-09-22 17:18:13 [DEBUG] [SP\Core\Crypt\Session::reKey] SP\Core\Crypt\Session::reKey
2018-09-22 17:18:14 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\AccountController::indexAction::Array
(
)

2018-09-22 17:18:14 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT Client.id, Client.name
            FROM Account
            RIGHT JOIN Client ON Account.clientId = Client.id
            WHERE Account.clientId IS NULL
            OR Client.isGlobal = 1
            OR (((Account.isPrivate IS NULL OR Account.isPrivate = 0 OR (Account.isPrivate = 1 AND Account.userId = ?)) AND (Account.isPrivateGroup IS NULL OR Account.isPrivateGroup = 0 OR (Account.isPrivateGroup = 1 AND Account.userGroupId = ?))))
            GROUP BY id
            ORDER BY Client.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT id, `name`, description, `hash` FROM Category ORDER BY `name`;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT id, `name`, `hash` FROM Tag ORDER BY `name`;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountSearchService::loadColors] Loaded accounts color cache
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT DISTINCT Account.* FROM account_search_v Account  WHERE (((Account.isPrivate IS NULL OR Account.isPrivate = 0 OR (Account.isPrivate = 1 AND Account.userId = ?)) AND (Account.isPrivateGroup IS NULL OR Account.isPrivateGroup = 0 OR (Account.isPrivateGroup = 1 AND Account.userGroupId = ?))))  ORDER BY Account.clientName, Account.name ASC LIMIT ?, ?;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT accountId, userId FROM AccountToFavorite WHERE userId = ?;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id, U.name, U.login, AU.isEdit
            FROM AccountToUser AU
            INNER JOIN User U ON AU.userId = U.id
            WHERE AU.accountId = ?
            ORDER BY U.name;
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT G.id, G.name, AUG.isEdit
            FROM AccountToUserGroup AUG
            INNER JOIN UserGroup G ON AUG.userGroupId = G.id
            WHERE AUG.accountId = ?
            ORDER BY G.name;
2018-09-22 17:18:14 [DEBUG] [SP\Services\Account\AccountAclService::getAcl] Account ACL HIT
2018-09-22 17:18:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT T.id, T.name
                FROM AccountToTag AT
                INNER JOIN Tag T ON AT.tagId = T.id
                WHERE AT.accountId = ?
                ORDER BY T.name;

`

same missing error output in /var/log/apache2

Do you have an idea?

regards, Mario

**Comment by nuxsmin** [comment]
Hello Mario, though there isn't a named release yet, you would need to update to the current pushed build which is 18091801. It should fix some issues.

Kind regards

**Comment by vmario89** [comment]
Hi @nuxsmin ,

i checked out the latest commit from devel-3.0 branch. But the issue is not fixed. The actions still cause JSON.parser Error

```
2018-09-24 20:13:02 [EXCEPTION] [N/A] Acción no encontrada
#0 /var/www/vhosts/pw.fablabchemnitz.de/lib/SP/Core/Acl/Acl.php(79): SP\Core\Acl\Actions->getActionById(1806)
#1 /var/www/vhosts/pw.fablabchemnitz.de/app/modules/web/Controllers/Helpers/Grid/ItemPresetGrid.php(277): SP\Core\Acl\Acl::getActionRoute(1806)
#2 /var/www/vhosts/pw.fablabchemnitz.de/app/modules/web/Controllers/Helpers/Grid/ItemPresetGrid.php(73): SP\Modules\Web\Controllers\Helpers\Grid\ItemPresetGrid->getDeleteAction()
#3 /var/www/vhosts/pw.fablabchemnitz.de/app/modules/web/Controllers/ItemManagerController.php(233): SP\Modules\Web\Controllers\Helpers\Grid\ItemPresetGrid->getGrid(Object(SP\Storage\Database\QueryResult))
#4 /var/www/vhosts/pw.fablabchemnitz.de/app/modules/web/Controllers/ItemManagerController.php(115): SP\Modules\Web\Controllers\ItemManagerController->getItemPresetList()
#5 /var/www/vhosts/pw.fablabchemnitz.de/app/modules/web/Controllers/ItemManagerController.php(70): SP\Modules\Web\Controllers\ItemManagerController->getGridTabs()
#6 [internal function]: SP\Modules\Web\Controllers\ItemManagerController->indexAction()
#7 /var/www/vhosts/pw.fablabchemnitz.de/lib/SP/Bootstrap.php(222): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/vhosts/pw.fablabchemnitz.de/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/vhosts/pw.fablabchemnitz.de/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/vhosts/pw.fablabchemnitz.de/lib/SP/Bootstrap.php(432): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/vhosts/pw.fablabchemnitz.de/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/vhosts/pw.fablabchemnitz.de/index.php(28): require('/var/www/vhosts...')
#14 {main}
```

**Comment by nuxsmin** [comment]
Umm, okay, It seems that the actions cache did not refresh. Please, delete the `actions.cache` within `app/cache` directory.

Regards

**Comment by vmario89** [comment]
hi. this did not help. i deleted the whole cache dir. makes no difference :(

**Comment by nuxsmin** [comment]
It should, since action Id is included in https://github.com/nuxsmin/sysPass/blob/ca620b60fb2327fca72d61b4377d44ca26ae422a/app/config/actions.xml#L862 file

**Comment by vmario89** [comment]
Hi,
i restarted Apache2 and reloaded the app. The errors still occure but with some small difference as i have seen. The errors occure on every action selection of this drop down menu

![grafik](https://user-images.githubusercontent.com/5631071/45997359-9a8c0200-c09f-11e8-86a0-40a47fbd538c.png)

**Comment by nuxsmin** [comment]
Hi, has the `actions.cache` file been generated?. Has the config/cache directory the correct permissions?. This is really weird, since your config file does not have the current version number set (you told me on another issue).

**Comment by vmario89** [comment]
Hey nux,

i found the error for this! My actions.xml in /app/config was old. I copied it from my backup to the instance. My workflow to upgrade my syspass instance is as following:

1. pull latest data from syspass repo into local clone
2. make backup of mysql database
3. make backup of /var/www files
4. write new files from git repo to /var/www with deleting old files (to avoid having dangling old unrequired files ald folders dueto renamings/changes)
5. copy back config files from backup to the instance

This was my mistake. I've just overwritten newer repo file with old one

I got only one problem. You already figured it out in your last comment: in my config.xml and in database too (table "config", column value "version") is still an old  version value "300.18073101"
config.xml:
  <configVersion>300.18073101</configVersion>
  <databaseVersion>300.18073101</databaseVersion>

I could try to update them manually. Does this have any side effects? The table structure in sql is already up to date because partially i did it by hand.

regards, Mario

**Comment by nuxsmin** [comment]
Hi Mario, no worries, I'm glad to know the actions issue was solved.

Regarding the database upgrade, it could be done manually, since there isn't any aux upgrade (done through code), but it sounds me really weird, because every update on the demo site triggered the upgrade process, so I'm wondering why it isn't so in your instance.

Please, update the build number (last 8 digits of the sql file name) in your config file after upgrading the database.

Regards

**Comment by vmario89** [comment]
Hi nux,
the database upgrade was triggered after i did updating the files on the web server. it opened automatically /index.php?r=upgrade

i entered the upgradeKey i put in config.xml and then it logged me into syspass. But the versions did not change. But i cannot say since how long this issue is lasting. maybe it belongs to some older version and does not occure in never versions. I don't know. i will try to fix the version strings tomorrow and for next upgrade process i will have a more detailed look again

**Comment by vmario89** [comment]
ticket can be closed i think. see also https://github.com/nuxsmin/sysPass/issues/1040. belongs together due to upgrade procedure failure

**Comment by nuxsmin** [comment]
Fine, thanks!

**Comment by vmario89** [comment]
Hi nuxmin,

i think there is a problem which is not solved. I recognized updating my instance did not update the version on config.xml and sql properly. I still cannot find the reason but i can show you what my automation does:

``
22:27:49 ✔ root@git-droid:/opt/sysPass-Update# /opt/sysPass-Update/update.sh -ci=$COMMIT -su=syspass -p=/var/www/vhosts/pw.thedomain.de
Creating MariaDB backup
Making copy of application files ...
/opt/sysPass-Update/update.sh: line 79: [[!: command not found
Updating local sysPass git repo clone ...
fatal: destination path 'sysPass' already exists and is not an empty directory.
No stash entries found.
No local changes to save
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

Checking out provided commit id ...
HEAD is now at c503baa4 * [MOD] Code refactoring * [ADD] Added PHP 7.2 to Travis CI
HEAD is now at c503baa4 * [MOD] Code refactoring * [ADD] Added PHP 7.2 to Travis CI
Syncing new files to target directory ...
Copying back config files from backup directory to target directory ...
Re-Overwriting config files from git repo to current syspass instance ...
Getting Composer ...
All settings correct for using Composer
Downloading...

Composer (version 1.7.2) successfully installed to: /var/www/vhosts/pw.thedomain.de/composer.phar
Use it: php composer.phar

Installing Composer modules ...
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 65 installs, 0 updates, 0 removals
  - Installing ademarre/binary-to-text-php (dev-master 5d98d17): Cloning 5d98d17be1 from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing defuse/php-encryption (v2.2.1): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/inflector (v1.2.0): Loading from cache
  - Installing doctrine/collections (v1.4.0): Loading from cache
  - Installing doctrine/cache (v1.6.2): Loading from cache
  - Installing doctrine/annotations (v1.4.0): Loading from cache
  - Installing doctrine/common (v2.7.3): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing klein/klein (v2.1.2): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing php-di/phpdoc-reader (2.1.0): Loading from cache
  - Installing php-di/invoker (2.0.0): Loading from cache
  - Installing nikic/php-parser (v4.0.3): Loading from cache
  - Installing symfony/polyfill-util (v1.9.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.9.0): Loading from cache
  - Installing jeremeamia/superclosure (2.4.0): Loading from cache
  - Installing php-di/php-di (6.0.3): Loading from cache
  - Installing phpmailer/phpmailer (v6.0.5): Loading from cache
  - Installing phpseclib/phpseclib (2.0.11): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.9.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.9.0): Loading from cache
  - Installing symfony/dom-crawler (v3.4.14): Loading from cache
  - Installing symfony/css-selector (v3.4.14): Loading from cache
  - Installing symfony/browser-kit (v3.4.14): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing fabpot/goutte (v3.2.3): Loading from cache
  - Installing fzaninotto/faker (v1.8.0): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing symfony/yaml (v3.4.14): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (6.5.12): Loading from cache
  - Installing phpunit/dbunit (3.0.3): Loading from cache
  - Installing symfony/debug (v3.4.14): Loading from cache
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
php-di/php-di suggests installing ocramius/proxy-manager (Install it if you want to use lazy injection (version ~2.0))
phpmailer/phpmailer suggests installing hayageek/oauth2-yahoo (Needed for Yahoo XOAUTH2 authentication)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
phpmailer/phpmailer suggests installing stevenmaguire/oauth2-microsoft (Needed for Microsoft XOAUTH2 authentication)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
symfony/browser-kit suggests installing symfony/process
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
Generating autoload files
Could not open input file: compuser.phar
Removing Cache (there should be no cache through rsync!)...
Restarting apache to remove old gettext translation fragments ...
Generating translation .pot file ...
Version check from MariaDB:
+--------------+
| value        |
+--------------+
| 300.18093001 |
+--------------+
Version check from config.xml:
  <configVersion>300.18093001</configVersion>
  <databaseVersion>300.18093001</databaseVersion>
Creating and inserting new upgrade key ...
The upgrade key is:
f9a1c4e36a127d6731ac4543199e4af9
Double Check:
  <upgradeKey>f9a1c4e36a127d6731ac4543199e4af9</upgradeKey>
``

This output is fullly done by my update script i wrote: https://leyghis.fablabchemnitz.de:8444/MarioVoigt/sysPass-Update 

When i enter the upgradeKey syspass does the updae and continues to login mask but the values are not changed

![grafik](https://user-images.githubusercontent.com/5631071/46375212-1505e480-c693-11e8-9ba3-291fd10c278b.png)
![grafik](https://user-images.githubusercontent.com/5631071/46375216-17683e80-c693-11e8-816c-86e2c87f977a.png)
