### ISSUE TITLE
Another one with LDAP issue

### ISSUE THREAD

**Issue by alexseys** [nuxsmin/sysPass#1099]
Hi All, 
First of all, 
Very exiting program, has tons of features I seek.
Beta version chosen as latest and greatest. I did not try v2.

**sysPass Version**
sysPass version	3.0-beta (300.18110601)
Database	SERVER_VERSION : 5.5.60-MariaDB 
CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id:  $ 
CONNECTION_STATUS : Localhost via UNIX socket 
Name: sysPass@localhost
PHP	Version: 7.2.12 

**Describe the question**
Once LDAP config is created and saved, LDAP users as well as local users are not allowed to login with BIND errors ( log below), web interface shows: 
Connection error (BIND)
Invalid credentials (49)

I tried diff format for LDAP user: cn=..., user@domain , username etc... no luck 
So was wandering what's the proper config for LDAP?
I have for example ansible tower running with same creds with no issues.

Thank you

**Platform (please complete the following information):**
 - OS: Centos 7
 - OS Version: 3.10.0-862.14.4.el7.x86_64
 - Browser: Firefox, Chrome, Safari

**Additional context**

2018-11-12 19:31:47 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-12 19:31:47 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-11-12 19:31:47 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-12 19:31:47 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-12 19:31:47 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-12 19:31:47 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-12 19:31:47 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-12 19:31:47 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-12 19:31:47 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-12 19:31:47 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-12 19:31:47 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-12 19:31:47 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-12 19:31:47 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-12 19:31:47 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-12 19:31:47 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-12 19:31:47 [DEBUG] [SP\Core\Crypt\Session::reKey] SP\Core\Crypt\Session::reKey
2018-11-12 19:31:48 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-11-12 19:31:48 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-12 19:31:48 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-12 19:31:49 [EXCEPTION] [N/A] Connection error (BIND)
#0 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(110): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(91): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/lib/SP/Services/Ldap/LdapCheckService.php(55): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/app/modules/web/Controllers/ConfigLdapController.php(147): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCo
llection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/lib/SP/Bootstrap.php(463): Klein\Klein->dispatch(Object(Klein\Request))
#10 /var/www/html/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#11 /var/www/html/index.php(28): require('/var/www/html/l...')
#12 {main}

**Comment by nuxsmin** [comment]
Hello , I'm glad that you found sysPass useful :)

Please, check out the latest commits, since this issue has been fixed (among other features). It was caused by a wrong behavior when LDAP filtering group wasn't set.

Regards.

**Comment by alexseys** [comment]
Thank you for quick response!I've got file via zip on your site.Let me try git then.
    On Monday, November 12, 2018, 2:48:03 PM EST, RubénD <notifications@github.com> wrote:  
 
 
Hello , I'm glad that you found sysPass useful :)

Please, check out the latest commits, since this issue has been fixed (among other features). It was caused by a wrong behavior when LDAP filtering group wasn't set.

Regards.

**Comment by alexseys** [comment]
No clue what happened this thing started to work?!?!?!

**Comment by alexseys** [comment]
Here is version I was able to pul today, same issue persists, is that correct version?

Connection error (BIND)
Invalid credentials (49)

sysPass version | 3.0-rc1 (300.18111203)
-- | --
Database | SERVER_VERSION : 5.5.60-MariaDB CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 -  CONNECTION_STATUS : Localhost via UNIX socket 
Name: syspass@localhost

LOG File:
2018-11-14 04:00:55 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-14 04:00:55 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-14 04:00:55 [EXCEPTION] [N/A] Connection error (BIND)
#0 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/lib/SP/Services/Ldap/LdapCheckService.php(55): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/app/modules/web/Controllers/ConfigLdapController.php(151): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/lib/SP/Bootstrap.php(466): Klein\Klein->dispatch(Object(Klein\Request))
#10 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /var/www/html/index.php(28): require('/var/www/html/l...')
#12 {main}
2018-11-14 04:00:55 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Connection error (BIND)

**Comment by alexseys** [comment]
Yes using ADS
According to this from /var/log/httpd/error_log, ldap resolves and connects
Any thoughts? I'll try direct IP address tomorrow.

ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_err2string
ldap_err2string
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/openldap/ldap.conf
ldap_init: using /etc/openldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldap://ldap.server.com)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP ldap.server.com:389
ldap_new_socket: 20
ldap_prepare_socket: 20
ldap_connect_to_host: Trying 172.27.33.80:389
ldap_pvt_connect: fd: 20 tm: 10 async: 0
ldap_ndelay_on: 20
attempting to connect:
connect errno: 115
ldap_int_poll: fd: 20 tm: 10
ldap_is_sock_ready: 20
ldap_ndelay_off: 20
ldap_pvt_connect: 0
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x55a0e2b7e330 msgid 1
wait4msg ld 0x55a0e2b7e330 msgid 1 (infinite timeout)
wait4msg continue ld 0x55a0e2b7e330 msgid 1 all 1
** ld 0x55a0e2b7e330 Connections:
* host: ldap.partners.org  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Tue Nov 13 23:53:55 2018


** ld 0x55a0e2b7e330 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55a0e2b7e330 request count 1 (abandoned 0)
** ld 0x55a0e2b7e330 Response Queue:
   Empty
  ld 0x55a0e2b7e330 response count 0
ldap_chkResponseList ld 0x55a0e2b7e330 msgid 1 all 1
ldap_chkResponseList returns ld 0x55a0e2b7e330 NULL
ldap_int_select
read1msg: ld 0x55a0e2b7e330 msgid 1 all 1
read1msg: ld 0x55a0e2b7e330 msgid 1 message type bind
read1msg: ld 0x55a0e2b7e330 0 new referrals
read1msg:  mark request completed, ld 0x55a0e2b7e330 msgid 1
request done: ld 0x55a0e2b7e330 msgid 1
res_errno: 49, res_error: <80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1>, res_matched: <>

**Comment by nuxsmin** [comment]
Hello, the last line contains the error code: 


```res_errno: 49, res_error: <80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1>, res_matched: <>```


https://stackoverflow.com/questions/31411665/ldap-error-code-49-80090308-ldaperr-dsid-0c0903a9-comment-acceptsecurityc#40510857

**Comment by alexseys** [comment]
Here is the thing if i use this code just to test my creds from command line works fine, i get success with proper creds and error with wrong ones, so as far as creds concerned they are correct.
Do you have a doc where proper permissions are listed out for app/*?
Do you have a doc where proper selinux settings are listed out for app/* ( selinux is disabled at this time)?
Do you have a doc where correct AD LDAP settings are listed ( ones that work in your environment)?

<?php

// using ldap bind
$ldaprdn  = 'cn=user,cn=users,dc=server,dc=com';     // ldap rdn or dn
$ldappass = 'ldjfhskdjfh';  // associated password

// connect to ldap server
$ldapconn = ldap_connect("ldap.server.com")
    or die("Could not connect to LDAP server.");

if ($ldapconn) {

    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful... $ldapbind";
    } else {
        echo "LDAP bind failed...";
    }

}

?>


Thank you

**Comment by alexseys** [comment]
After updating today still have LDAP problems, though there is a change:
if i open config LDAP page and fill out information and test, i get LDAP connection OK 0 records returned;
the search base and group configured so:
CN=Users,DC=partners,DC=org
user: 
cn=user,CN=Users,DC=partners,DC=org

As soon as i change group dn to something else i.e.:
CN=group,CN=Users,DC=partners,DC=org
I get: Error while searching the group RDN

Also as soon as I save this config, I get back original error.
here some logs:


before save:
/var/log/httpd/error_log:

ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/openldap/ldap.conf
ldap_init: using /etc/openldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldap://ldap.company.com)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP ldap.company.com:389
ldap_new_socket: 22
ldap_prepare_socket: 22
ldap_connect_to_host: Trying 172.27.33.83:389
ldap_pvt_connect: fd: 22 tm: 10 async: 0
ldap_ndelay_on: 22
attempting to connect:
connect errno: 115
ldap_int_poll: fd: 22 tm: 10
ldap_is_sock_ready: 22
ldap_ndelay_off: 22
ldap_pvt_connect: 0
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x55ae647cec50 msgid 1
wait4msg ld 0x55ae647cec50 msgid 1 (infinite timeout)
wait4msg continue ld 0x55ae647cec50 msgid 1 all 1
** ld 0x55ae647cec50 Connections:
* host: ldap.company.com  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Mon Nov 19 14:12:36 2018


** ld 0x55ae647cec50 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55ae647cec50 request count 1 (abandoned 0)
** ld 0x55ae647cec50 Response Queue:
   Empty
  ld 0x55ae647cec50 response count 0
ldap_chkResponseList ld 0x55ae647cec50 msgid 1 all 1
ldap_chkResponseList returns ld 0x55ae647cec50 NULL
ldap_int_select
read1msg: ld 0x55ae647cec50 msgid 1 all 1
read1msg: ld 0x55ae647cec50 msgid 1 message type bind
read1msg: ld 0x55ae647cec50 0 new referrals
read1msg:  mark request completed, ld 0x55ae647cec50 msgid 1
request done: ld 0x55ae647cec50 msgid 1
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_search_ext
put_filter: "(&(|(memberOf=cn=users,dc=company,dc=com)(groupMembership=cn=users,dc=company,dc=com))(|(objectClass=inetcomPerson)(objectClass=person)(objectClass=simpleSecurityObject)))"
put_filter: AND
put_filter_list "(|(memberOf=cn=users,dc=company,dc=com)(groupMembership=cn=users,dc=company,dc=com))(|(objectClass=inetcomPerson)(objectClass=person)(objectClass=simpleSecurityObject))"
put_filter: "(|(memberOf=cn=users,dc=company,dc=com)(groupMembership=cn=users,dc=company,dc=com))"
put_filter: OR
put_filter_list "(memberOf=cn=users,dc=company,dc=com)(groupMembership=cn=users,dc=company,dc=com)"
put_filter: "(memberOf=cn=users,dc=company,dc=com)"
put_filter: simple
put_simple_filter: "memberOf=cn=users,dc=company,dc=com"
put_filter: "(groupMembership=cn=users,dc=company,dc=com)"
put_filter: simple
put_simple_filter: "groupMembership=cn=users,dc=company,dc=com"
put_filter: "(|(objectClass=inetcomPerson)(objectClass=person)(objectClass=simpleSecurityObject))"
put_filter: OR
put_filter_list "(objectClass=inetcomPerson)(objectClass=person)(objectClass=simpleSecurityObject)"
put_filter: "(objectClass=inetcomPerson)"
put_filter: simple
put_simple_filter: "objectClass=inetcomPerson"
put_filter: "(objectClass=person)"
put_filter: simple
put_simple_filter: "objectClass=person"
put_filter: "(objectClass=simpleSecurityObject)"
put_filter: simple
put_simple_filter: "objectClass=simpleSecurityObject"
ldap_build_search_req ATTRS: dn
ldap_send_initial_request
ldap_send_server_request
ldap_result ld 0x55ae647cec50 msgid 2
wait4msg ld 0x55ae647cec50 msgid 2 (infinite timeout)
wait4msg continue ld 0x55ae647cec50 msgid 2 all 1
** ld 0x55ae647cec50 Connections:
* host: ldap.company.com  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Mon Nov 19 14:12:36 2018


** ld 0x55ae647cec50 Outstanding Requests:
 * msgid 2,  origid 2, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55ae647cec50 request count 1 (abandoned 0)
** ld 0x55ae647cec50 Response Queue:
   Empty
  ld 0x55ae647cec50 response count 0
ldap_chkResponseList ld 0x55ae647cec50 msgid 2 all 1
ldap_chkResponseList returns ld 0x55ae647cec50 NULL
ldap_int_select
read1msg: ld 0x55ae647cec50 msgid 2 all 1
read1msg: ld 0x55ae647cec50 msgid 2 message type search-result
read1msg: ld 0x55ae647cec50 0 new referrals
read1msg:  mark request completed, ld 0x55ae647cec50 msgid 2
request done: ld 0x55ae647cec50 msgid 2
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 2, msgid 2)
ldap_parse_result
ldap_parse_result
ldap_msgfree
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed

syspass.log:

2018-11-19 19:12:35 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 19:14:01 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 19:14:01 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 19:14:01 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 19:14:01 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 19:14:01 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 19:14:01 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 19:14:01 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 19:14:01 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 19:14:01 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 19:14:01 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 19:14:01 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 19:14:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 19:14:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 19:14:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 19:14:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 19:14:01 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array


After hitting save:

error_log:

wait4msg continue ld 0x55ae646043c0 msgid 1 all 1
** ld 0x55ae646043c0 Connections:
* host: ldap.company.com  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Mon Nov 19 14:17:15 2018


** ld 0x55ae646043c0 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55ae646043c0 request count 1 (abandoned 0)
** ld 0x55ae646043c0 Response Queue:
   Empty
  ld 0x55ae646043c0 response count 0
ldap_chkResponseList ld 0x55ae646043c0 msgid 1 all 1
ldap_chkResponseList returns ld 0x55ae646043c0 NULL
ldap_int_select
read1msg: ld 0x55ae646043c0 msgid 1 all 1
read1msg: ld 0x55ae646043c0 msgid 1 message type bind
read1msg: ld 0x55ae646043c0 0 new referrals
read1msg:  mark request completed, ld 0x55ae646043c0 msgid 1
request done: ld 0x55ae646043c0 msgid 1
res_errno: 49, res_error: <80090308: LdapErr: DSID-0C090400, com

syspass.log:

2018-11-19 19:17:14 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 19:17:15 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-19 19:17:15 [EXCEPTION] [N/A] Connection error (BIND)
#0 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/lib/SP/Services/Ldap/LdapCheckService.php(55): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/app/modules/web/Controllers/ConfigLdapController.php(151): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#10 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /var/www/html/index.php(28): require('/var/www/html/l...')
#12 {main}
2018-11-19 19:17:15 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Connection error (BIND)
2018-11-19 19:18:01 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 19:18:01 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 19:18:01 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 19:18:01 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 19:18:01 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 19:18:01 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 19:18:01 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 19:18:01 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 19:18:01 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 19:18:01 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 19:18:01 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 19:18:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 19:18:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 19:18:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 19:18:01 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 19:18:01 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array



If before saving I try to point to a particular group, i.e.: CN=group,CN=Users,DC=company,DC=com: 

syspass.log:
2018-11-19 19:20:19 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 19:20:19 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 19:20:19 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 19:20:19 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 19:20:19 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 19:20:19 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 19:20:19 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 19:20:19 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 19:20:19 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 19:20:19 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 19:20:19 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 19:20:19 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 19:20:19 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 19:20:19 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 19:20:19 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 19:20:19 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-11-19 19:20:19 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 19:20:20 [EXCEPTION] [N/A] Error while searching the group RDN
#0 /var/www/html/lib/SP/Providers/Auth/Ldap/Ldap.php(145): SP\Providers\Auth\Ldap\LdapActions->searchGroupsDn('(|(objectClass=...')
#1 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapStd.php(69): SP\Providers\Auth\Ldap\Ldap->getGroupDn()
#2 /var/www/html/lib/SP/Services/Ldap/LdapCheckService.php(80): SP\Providers\Auth\Ldap\LdapStd->getGroupMembershipFilter()
#3 /var/www/html/app/modules/web/Controllers/ConfigLdapController.php(153): SP\Services\Ldap\LdapCheckService->getObjects(false)
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#10 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /var/www/html/index.php(28): require('/var/www/html/l...')
#12 {main}
2018-11-19 19:20:20 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Error while searching the group RDN

error_log:

ldap_int_select
read1msg: ld 0x55ae646062d0 msgid 1 all 1
read1msg: ld 0x55ae646062d0 msgid 1 message type bind
read1msg: ld 0x55ae646062d0 0 new referrals
read1msg:  mark request completed, ld 0x55ae646062d0 msgid 1
request done: ld 0x55ae646062d0 msgid 1
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_search_ext
put_filter: "(&(cn=group,CN=Users,DC=company,DC=com)(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)))"
put_filter: AND
put_filter_list "(cn=group,CN=Users,DC=company,DC=com)(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group))"
put_filter: "(cn=group,CN=Users,DC=company,DC=com)"
put_filter: simple
put_simple_filter: "cn=group,CN=Users,DC=company,DC=com"
put_filter: "(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group))"
put_filter: OR
put_filter_list "(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)"
put_filter: "(objectClass=groupOfNames)"
put_filter: simple
put_simple_filter: "objectClass=groupOfNames"
put_filter: "(objectClass=groupOfUniqueNames)"
put_filter: simple
put_simple_filter: "objectClass=groupOfUniqueNames"
put_filter: "(objectClass=group)"
put_filter: simple
put_simple_filter: "objectClass=group"
ldap_build_search_req ATTRS: dn
ldap_send_initial_request
ldap_send_server_request
ldap_result ld 0x55ae646062d0 msgid 2
wait4msg ld 0x55ae646062d0 msgid 2 (infinite timeout)
wait4msg continue ld 0x55ae646062d0 msgid 2 all 1
** ld 0x55ae646062d0 Connections:
* host: ldap.company.com  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Mon Nov 19 14:20:20 2018


** ld 0x55ae646062d0 Outstanding Requests:
 * msgid 2,  origid 2, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55ae646062d0 request count 1 (abandoned 0)
** ld 0x55ae646062d0 Response Queue:
   Empty
  ld 0x55ae646062d0 response count 0
ldap_chkResponseList ld 0x55ae646062d0 msgid 2 all 1
ldap_chkResponseList returns ld 0x55ae646062d0 NULL
ldap_int_select
read1msg: ld 0x55ae646062d0 msgid 2 all 1
read1msg: ld 0x55ae646062d0 msgid 2 message type search-result
read1msg: ld 0x55ae646062d0 0 new referrals
read1msg:  mark request completed, ld 0x55ae646062d0 msgid 2
request done: ld 0x55ae646062d0 msgid 2
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 2, msgid 2)
ldap_parse_result
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed

**Comment by alexseys** [comment]
Current version:

sysPass version | 3.0-rc4 (300.18111902)

**Comment by nuxsmin** [comment]
Is there any message in sysPass event log (web)?, Please add `ldap.` to events list on config section and check again the LDAP connection.

**Comment by alexseys** [comment]
I have cleaned syslog
emptied config.xml from all ldap stuff
added ldap to events 
configured ldap and ran test that was successfull 
saved config ran test again and it failed with error 49
Here is full log file i have:


2018-11-19 21:46:17 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:17 [DEBUG] [SP\Storage\File\FileHandler::lock] File locked: /var/www/html/app/cache/config.cache
2018-11-19 21:46:17 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-11-19 21:46:17 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:46:17 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:46:17 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:17 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:46:17 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:46:17 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:17 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:46:18 [DEBUG] [SP\Storage\File\FileHandler::lock] File locked: /var/www/html/app/cache/secure_session/5bf2d684b165b8.79225751
2018-11-19 21:46:18 [DEBUG] [SP\Services\Crypt\SecureSessionService::saveKey] Saved session key
2018-11-19 21:46:18 [DEBUG] [SP\Core\Crypt\Crypt::decrypt] Ciphertext has invalid hex encoding.
2018-11-19 21:46:18 [DEBUG] [SP\Core\Crypt\CryptSessionHandler::read] Ciphertext has invalid hex encoding.
2018-11-19 21:46:18 [DEBUG] [SP\Core\Crypt\CryptSessionHandler::read] Session data not encrypted.
2018-11-19 21:46:18 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:18 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:46:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:46:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:46:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:46:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:46:18 [DEBUG] [SP\Core\Crypt\Session::reKey] SP\Core\Crypt\Session::reKey
2018-11-19 21:46:19 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\AccountController::indexAction::Array
(
)

2018-11-19 21:46:19 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:46:19 [EXCEPTION] [N/A] Unable to read/write file (/var/www/html/app/cache/colors.cache)
#0 /var/www/html/lib/SP/Storage/File/FileCache.php(40): SP\Storage\File\FileHandler->checkIsReadable()
#1 /var/www/html/lib/SP/Services/Account/AccountSearchService.php(427): SP\Storage\File\FileCache->load()
#2 /var/www/html/lib/SP/Services/Account/AccountSearchService.php(418): SP\Services\Account\AccountSearchService->loadColors()
#3 /var/www/html/lib/SP/Services/Service.php(78): SP\Services\Account\AccountSearchService->initialize()
#4 /var/www/html/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(142): SP\Services\Service->__construct(Object(DI\Container))
#5 /var/www/html/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#6 /var/www/html/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#7 /var/www/html/vendor/php-di/php-di/src/Container.php(377): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#8 /var/www/html/vendor/php-di/php-di/src/Container.php(137): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#9 /var/www/html/app/modules/web/Controllers/Helpers/Account/AccountSearchHelper.php(150): DI\Container->get('SP\\Services\\Acc...')
#10 /var/www/html/app/modules/web/Controllers/AccountController.php(90): SP\Modules\Web\Controllers\Helpers\Account\AccountSearchHelper->getAccountSearch()
#11 [internal function]: SP\Modules\Web\Controllers\AccountController->indexAction()
#12 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#13 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#14 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#15 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#16 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#17 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#18 /var/www/html/index.php(28): require('/var/www/html/l...')
#19 {main}
2018-11-19 21:46:22 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:22 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:46:22 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:46:22 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:46:22 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:22 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:46:22 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:46:22 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:22 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:46:22 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:22 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:46:22 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:46:22 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:46:22 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:46:22 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:46:22 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigManagerController::indexAction::Array
(
)

2018-11-19 21:46:22 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:46:22 [INFO] [SP\Core\MimeTypes::loadCache] Loaded MIME types cache
2018-11-19 21:46:22 [WARN] [SP\Mvc\View\Template::SP\Mvc\View\{closure}] Unable to retrieve "taskId" variable
2018-11-19 21:46:23 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:23 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:46:23 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:46:23 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:46:23 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:23 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:46:23 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:46:23 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:23 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:46:24 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:24 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:46:24 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:46:24 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:46:24 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:46:24 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:46:24 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array
(
)

2018-11-19 21:46:24 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:46:33 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:33 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:46:33 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:46:33 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:46:33 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:33 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:46:33 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:46:33 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:33 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:46:33 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:33 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:46:33 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigGeneralController::saveAction::Array
(
)

2018-11-19 21:46:33 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:46:33 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-19 21:46:33 [DEBUG] [SP\Storage\File\FileHandler::lock] File locked: /var/www/html/app/cache/config.cache
2018-11-19 21:46:34 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] save.config.general;;
2018-11-19 21:46:34 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:34 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:46:34 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:46:34 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:46:34 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:34 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:46:34 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:46:34 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:34 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:46:34 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:34 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:46:34 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:46:34 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:46:34 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:46:34 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:46:34 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigManagerController::indexAction::Array
(
)

2018-11-19 21:46:34 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:46:34 [INFO] [SP\Core\MimeTypes::loadCache] Loaded MIME types cache
2018-11-19 21:46:34 [WARN] [SP\Mvc\View\Template::SP\Mvc\View\{closure}] Unable to retrieve "taskId" variable
2018-11-19 21:46:53 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:53 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:46:53 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:46:53 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:46:53 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:53 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:46:54 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:46:54 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:46:54 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:46:54 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:46:54 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:46:54 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:46:54 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:46:54 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:46:54 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:46:54 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-11-19 21:46:54 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:47:02 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:47:02 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:47:02 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:47:02 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:47:02 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:47:02 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:47:02 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:47:02 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:47:02 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:47:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:47:03 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:47:03 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:47:03 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:47:03 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:47:03 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:47:03 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigLdapController::saveAction::Array
(
)

2018-11-19 21:47:03 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:47:03 [DEBUG] [SP\Storage\File\FileHandler::lock] File locked: /var/www/html/app/cache/config.cache
2018-11-19 21:47:03 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] save.config.ldap;;
2018-11-19 21:47:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:47:03 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:47:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:47:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:47:03 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:47:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:47:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:47:03 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:47:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:47:04 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:47:04 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:47:04 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:47:04 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:47:04 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:47:04 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:47:04 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigManagerController::indexAction::Array
(
)

2018-11-19 21:47:04 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:47:04 [INFO] [SP\Core\MimeTypes::loadCache] Loaded MIME types cache
2018-11-19 21:47:04 [WARN] [SP\Mvc\View\Template::SP\Mvc\View\{closure}] Unable to retrieve "taskId" variable
2018-11-19 21:47:08 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:47:08 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-19 21:47:08 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-19 21:47:08 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-19 21:47:08 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:47:08 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-19 21:47:08 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-19 21:47:08 [DEBUG] [SP\Plugin\PluginManager::getPlugins] Plugin found: /var/www/html/app/modules/web/plugins/Authenticator
2018-11-19 21:47:08 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-19 21:47:08 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-19 21:47:08 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-19 21:47:08 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-19 21:47:08 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-19 21:47:08 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-19 21:47:08 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-19 21:47:08 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-11-19 21:47:08 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-19 21:47:09 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-19 21:47:09 [EXCEPTION] [N/A] Connection error (BIND)
#0 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/lib/SP/Services/Ldap/LdapCheckService.php(55): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/app/modules/web/Controllers/ConfigLdapController.php(151): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#10 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /var/www/html/index.php(28): require('/var/www/html/l...')
#12 {main}
2018-11-19 21:47:09 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Connection error (BIND)

**Comment by alexseys** [comment]
![image](https://user-images.githubusercontent.com/133041/48737125-34dd7180-ec1b-11e8-80a0-ff9726ae1c01.png)

**Comment by alexseys** [comment]
this is what i see when I run test and do not save config 
![image](https://user-images.githubusercontent.com/133041/48737370-cf3db500-ec1b-11e8-98b9-5b0fef2c656e.png)

**Comment by alexseys** [comment]
and this is right after i save:
![image](https://user-images.githubusercontent.com/133041/48737446-057b3480-ec1c-11e8-8c41-46be4f688558.png)

**Comment by nuxsmin** [comment]
Be aware that after saving the LDAP configuration, the bind password is replaced by *** but the real one is saved in config.xml file

**Comment by nuxsmin** [comment]
That being said, after saving you need to fill in again the LDAP password if you want to test it. 

It displayed 0 objects found, so LDAP users aren't found indeed...

**Comment by alexseys** [comment]
you're right, have to put password in do-uh!!
why would fail after config is saved?

**Comment by nuxsmin** [comment]
Hmm, which error did you mean?. If no objects were found, you won't be able to log in using LDAP, so it could be related to either a wrong group filter or wrong search base.

Regards

**Comment by alexseys** [comment]
Yeah, not putting password for test was dummy of me, forget about it.
Still most apparent issue if i were configure ldap with:

search base: CN=Users,DC=company,DC=com
group: cn=myadminsgroup,CN=Users,DC=company,DC=com

I get: 
2018-11-20 22:13:31 [EXCEPTION] [N/A] Error while searching the group RDN
#0 /var/www/html/lib/SP/Providers/Auth/Ldap/Ldap.php(145): SP\Providers\Auth\Ldap\LdapActions->searchGroupsDn('(objectCategory...')
#1 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapMsAds.php(60): SP\Providers\Auth\Ldap\Ldap->getGroupDn()
#2 /var/www/html/lib/SP/Services/Ldap/LdapCheckService.php(80): SP\Providers\Auth\Ldap\LdapMsAds->getGroupMembershipFilter()
#3 /var/www/html/app/modules/web/Controllers/ConfigLdapController.php(153): SP\Services\Ldap\LdapCheckService->getObjects(false)
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#10 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /var/www/html/index.php(28): require('/var/www/html/l...')
#12 {main}
2018-11-20 22:13:31 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Error while searching the group RDN

while tests using below config succeeds: 
search base: CN=Users,DC=company,DC=com
group: CN=Users,DC=company,DC=com

 but none of the users AD or local can login to syspass once config is saved.
I have seen a #1095 and will try devel-3.0 tomorrow 

Thank you.

**Comment by nuxsmin** [comment]
Hello, I've just pushed some fixes about LDAP issues. Please check it out and let me know if it works fine.

Thanks for the feedback!

**Comment by alexseys** [comment]
Thank you very much, Will be out tomorrow but once i get in right away :)  
Thank you
    On Sunday, November 25, 2018, 3:05:19 PM EST, RubénD <notifications@github.com> wrote:  
 
 
Hello, I've just pushed some fixes about LDAP issues. Please check it out and let me know if it works fine.

Thanks for the feedback!

**Comment by alexseys** [comment]
Hi 
For version:
3.0-rc5 (300.18112601)

LDAP is working, was able to login with AD user, thank  you, and all who helped to push this.



Thank you 
Alexsey

**Comment by nuxsmin** [comment]
Great news!
