### ISSUE TITLE
Error on account creation

### ISSUE THREAD

**Issue by riccimatic** [nuxsmin/sysPass#1828]
**sysPass Version**
3.2 (323.22052501)
Config: 323.22052501
App: 323.22052501
DB: 323.22052501

**Describe the bug**
Each account created (more tentative woth different values and combo) generate this error in main page (with search parameters or not):
syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ')'

**To Reproduce**
1. add new client (ie: Customer01)
2. add new category (ie: Microsoft 365)
3. add new account

Name: aaaa
Client: Customer01
Category: Microsoft 365
user: aaaa
passwd: aaaa

4. See error on search page

**Expected behavior**
See accounts and filter them

**Screenshots**
[screens.zip](https://github.com/nuxsmin/sysPass/files/8774847/screens.zip)

**Platform:**
 - OS: Windows
 - OS Version: Windows 10 Pro 21H2
 - Browser: Chrome 102.0.5005.63

**Additional context**
Self hosted machine on Azure

**Comment by nuxsmin** [comment]
Hello @riccimatic !!

This issue has been solved in latest release. Thanks for the notice and sorry for the inconvenience (I needed to fix another issue in a faster way).

Regards!

**Comment by psouza0** [comment]
With me the same problem persists.

**Comment by lebe-dev** [comment]
Problem has been appeared with the latest 3.2 docker image. Fresh installation.

Problem gone with 3.2.11

**Comment by petertweed** [comment]
@nuxsmin please tag another release.  
Latest works, but 3.2.3 is broken.

**Comment by vanhalain** [comment]
3.2.3 is still broken, i downgraded to 3.2.11 for it to work.
