### ISSUE TITLE
Unable to connect to the DB

### ISSUE THREAD

**Issue by ajtak-angelus** [nuxsmin/sysPass#220]
Hello,
I have a problem with sysPass instalation.
I follow the instruction:
http://wiki.syspass.org/en/install
I have Debian Wheezy.
After completing the data a got error message:
Please, check connection parameters.
SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
I have tried even Hosting mode - I have correct rights - and still error:
Please, check connection parameters.
SQLSTATE[28000] [1045] Access denied for user 'syspassu'@'localhost' (using password: YES)
Other applications work with database properly (SugarCRM etc.)
What else could cause the problem?
Thank You for Your help.

**Comment by nuxsmin** [comment]
Sorry for the late response, I've been very busy...

Did you tried it again?

**Comment by jcboysha** [comment]
I am also having this issue. Coming from line 101 DBConnectionFactory.class.php.

**Comment by nuxsmin** [comment]
Are you trying to connect to a remote database?

**Comment by jcboysha** [comment]
Local database.

**Comment by nuxsmin** [comment]
Ummm, are you using a database admin user to perform the config? (Latest config block fields)

Are you installing it on a hosting provider?

You can create the sysPass database owner and the database itself by your own and then check the hosting mode switch. There is a mini howto at wiki.syspass.org.

**Comment by jcboysha** [comment]
I am installing it in a self-maintained environment. I understand that it can be done manually, I was just hoping to alert a bug in the installation process.

**Comment by jcboysha** [comment]
I am using a db admin, as well.

**Comment by nuxsmin** [comment]
Sure, no doubt about it...

I've done a bunch of setups in several environments like debian, Ubuntu, centos, Gentoo, etc, and every issue found has been fixed.

Let me know a little bit about you environment

**Comment by jcboysha** [comment]
It is being hosted on an Ubuntu 14.04 server running an up-to-date apache2 installation, after running the apt-get to install all of the modules and the appropriate lermissions and ownership settings.

**Comment by nuxsmin** [comment]
Is there any tables in the database?

That error (by file and line number) means that the config file has been written and the connection parameters are being used from it, so there would be set a wrong parameter. Can you try to log into the database by using the config file parameters?

**Comment by nuxsmin** [comment]
Hi, did it work?

**Comment by ajtak-angelus** [comment]
I have updated sysPass to 1.2.0.12 but I have still the same problem

**Comment by nuxsmin** [comment]
Can you tell me some info about your running environment? (DB engine, OS, PHP, etc)

**Comment by nuxsmin** [comment]
Can you try out the latest commit?

**Comment by adityavadar** [comment]
Getting this error
No es posible conectar con la BD (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getResults
Caller 3: SP\Storage\DB\getResultsArray
Caller 4: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 5: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2018-06-14 13:14:24 - SQL : SELECT plugin_name FROM plugins WHERE BIN(plugin_enabled) = 1
2018-06-14 13:14:24 - Action: getResultsArray -- Description: Error while querying
No es posible conectar con la BD (0) -- Details: SQL : SELECT plugin_name FROM plugins WHERE BIN(plugin_enabled) = 1
2018-06-14 14:23:36 - Exception: No es posible conectar con la BD - Compruebe los datos de conexión
2018-06-14 14:23:36 - #0  SP\Storage\DB->prepareQueryData() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:105]
#2  SP\Storage\DB::getResults() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:81]
#3  SP\Storage\DB::getResultsArray() called at [/var/www/html/sysPass/inc/SP/Mgmt/Plugins/Plugin.class.php:287]
#4  SP\Mgmt\Plugins\Plugin->getEnabled() called at [/var/www/html/sysPass/inc/SP/Core/Plugin/PluginUtil.class.php:185]
#5  SP\Core\Plugin\PluginUtil::getEnabledPlugins() called at [/var/www/html/sysPass/ajax/ajax_getEnvironment.php:54]

**Comment by nuxsmin** [comment]
@adityavadar it seems that your database isn't reachable. Please, check the connection using sysPass user in config.xml file

**Comment by adityavadar** [comment]
@nuxsmin there is no config.xml file in my config directory only , "key.pem"  , "lost+found" , "pubkey.pem",  "syspass.log"
.

**Comment by nuxsmin** [comment]
@adityavadar hmm, it should be there. Which version are you running?

**Comment by adityavadar** [comment]
@nuxsmin i am currently using syspass 2.1

**Comment by nuxsmin** [comment]
@adityavadar if this file doesn't exist, there would be some more previous errors. Is it stored in anywhere out of the webserver public root?

**Comment by adityavadar** [comment]
i am deploying syspass on kubernetes , i convert docker-compose file into manifest using Kompose. is this creating any issues? can i get manifest file of syspass?

**Comment by nuxsmin** [comment]
There shouldn't be any issues running on kubernetes, since you only need a set of two Pods for app and database. You need to create a service pointing to the database (if two Pods are deployed or localhost if you use only one).

The yaml could be got from any example about a deploymentset or statefulset, so no need to convert from docker-compose

**Comment by adityavadar** [comment]
ok ,yes , but there isn't any config.xml , why ?
this is complete log
2018-05-29 11:25:21 - Setup log file: /var/www/html/sysPass/inc/../config/syspass.log
2018-05-29 11:25:21 - initError
2018-05-29 11:25:21 - The "/config" directory permissions are wrong
2018-05-29 11:25:21 - Current: 777 - Needed: 750
2018-05-29 11:26:03 - initError
2018-05-29 11:26:03 - The "/config" directory permissions are wrong
2018-05-29 11:26:03 - Current: 777 - Needed: 750
2018-05-29 11:32:34 - Exception: No es posible conectar con la BD - Compruebe los datos de conexión
2018-05-29 11:32:34 - #0  SP\Storage\DB->prepareQueryData() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:105]
#2  SP\Storage\DB::getResults() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:81]
#3  SP\Storage\DB::getResultsArray() called at [/var/www/html/sysPass/inc/SP/Mgmt/Plugins/Plugin.class.php:287]
#4  SP\Mgmt\Plugins\Plugin->getEnabled() called at [/var/www/html/sysPass/inc/SP/Core/Plugin/PluginUtil.class.php:185]
#5  SP\Core\Plugin\PluginUtil::getEnabledPlugins() called at [/var/www/html/sysPass/ajax/ajax_getEnvironment.php:54]

2018-05-29 11:32:34 - Error while querying
No es posible conectar con la BD (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getResults
Caller 3: SP\Storage\DB\getResultsArray
Caller 4: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 5: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2018-05-29 11:32:34 - SQL : SELECT plugin_name FROM plugins WHERE BIN(plugin_enabled) = 1
2018-05-29 11:32:34 - Action: getResultsArray -- Description: Error while querying
No es posible conectar con la BD (0) -- Details: SQL : SELECT plugin_name FROM plugins WHERE BIN(plugin_enabled) = 1
2018-05-29 14:19:41 - Exception: No es posible conectar con la BD - Compruebe los datos de conexión
2018-05-29 14:19:41 - #0  SP\Storage\DB->prepareQueryData() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:105]
#2  SP\Storage\DB::getResults() called at [/var/www/html/sysPass/inc/SP/Storage/DB.class.php:81]
#3  SP\Storage\DB::getResultsArray() called at [/var/www/html/sysPass/inc/SP/Mgmt/Plugins/Plugin.class.php:287]
#4  SP\Mgmt\Plugins\Plugin->getEnabled() called at [/var/www/html/sysPass/inc/SP/Core/Plugin/PluginUtil.class.php:185]
#5  SP\Core\Plugin\PluginUtil::getEnabledPlugins() called at [/var/www/html/sysPass/ajax/ajax_getEnvironment.php:54]

NOTE: i already applied needed 750 permission on config directory.
